export const actionTypes = {
  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_COMMENTS: "FETCH_COMMENTS",
  FETCH_ERROR: "FETCH_ERROR",
  GET_REQUEST: "GET_REQUEST",
  GET_COMMENTS: "GET_COMMENTS",
  CLEAR_COMMENTS: "CLEAR_COMMENTS",
  ADD_POST: "ADD_POST",
  ADD_COMMENT: "ADD_COMMENT",
  UPDATE_POST: "UPDATE_POST"
};
